name: Deploy Flask app to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on Ubuntu's latest version

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the correct Python version you want, e.g., '3.9'

      # Step 3: Install dependencies globally
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Step 4: Run the app to check if everything works
      - name: Run Flask app
        run: |
          python3 app.py
