name: Deploy Flask app to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Fail after 10 minutes if still running

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Set this to your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
